logging:
  level:
    root: INFO
    br.eti.archanjo: INFO
    org.springframework: INFO

spring:
  profiles:
    active: default
  application:
    name: velociraptor-service
  datasource:
    url: jdbc:mysql://vm.services:3306/velociraptor?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: q1w2e3
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true
  data:
    mongodb:
      host: vm.services
      database: velociraptor
      repositories:
        enabled: true
  redis:
    database: 6
    host: vm.services
    port: 6379
    timeout: 120000
    pool:
      max-active: 16
      max-idle: 4
      max-wait: -1

server:
  port: 8080
  session:
    cookie:
      path: /
      name: velociraptor
    persistent: true
  tomcat:
    remote-ip-header: X-Forwarded-For

velociraptor:
  httplimits:
    limit: 100
    page: 0
  default-redirect: http://www.skoob.com.br